services:
  sell_helper:
    image: ghcr.io/rokhlin/sell_helper:latest
    container_name: sell_helper
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3000
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=
      - AUTHORIZED_USERS=
      - GEMINI_API_KEY=
      - DATABASE_URL=file:/app/data/sell_helper.db
