services:
  sell_helper:
    image: ghcr.io/rokhlin/sell_helper:latest
    container_name: sell_helper
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - ./data/config/.env
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/sell_helper.db
